Added profile feature
dularion/streama-app pull request #8
Opened 2018-11-23 08:45 UTC by Maximbndrnk

- show available profiles;
- switch between profiles;
- refactor saving watching list, find by profiles;

2018-11-23 08:48 UTC, dularion commented
yay :) but we'll wait with merging this until the backend stuff is rdy-4-review too :)

2018-12-06 19:14 UTC, dularion commented
So somehow the profiles in the menu are all empty, but the amount is correct. Any chance you know why this is? 

![image](https://user-images.githubusercontent.com/936076/49606342-6a13ee80-f993-11e8-8dad-7ca1e4a653d6.png)

2018-12-06 19:22 UTC, dularion requested changes
Please check the review comments - I believe this is not quite finished yet but on a very good way! thanks already for the work youve put into it

2018-12-06 19:22 UTC, dularion commented on www/templates/main.html
> +          {{profile.profile_name}}
So somehow the profiles in the menu are all empty, but the amount is correct. Any chance you know why this is?

![image](https://user-images.githubusercontent.com/936076/49606414-99c2f680-f993-11e8-9ce1-d3d685e3fd81.png)

2018-12-06 19:22 UTC, dularion commented on www/templates/main.html
>          <ion-item menu-close ui-sref="main.dash" ng-click="mainVm.toggleSearch()">
It would be good if we saw the currently selected profile somewhere in the header - maybe instead of the lines, like so:


![image](https://user-images.githubusercontent.com/936076/49606515-de4e9200-f993-11e8-9f96-324779f05680.png)

2018-12-06 19:22 UTC, dularion commented on www/js/core/services/api.service.js
> +        }
you dont need most of these endpoints, correct? `update`, `save`, `delete` are all not used here

2018-12-06 19:22 UTC, dularion commented on www/js/core/services/api.service.js
> +          });
was this even changed at all?

2018-12-06 19:22 UTC, dularion commented on www/js/core/main.controller.js
> +    $state.go('main.dash',{},{reload:true})
missing semicolon

2018-12-06 19:22 UTC, dularion commented on www/js/core/main.controller.js
> +    window.open(localStorageService.get('streamaDomain') + '#/sub-profiles', '_system')
missing semicolon

2018-12-06 19:22 UTC, dularion commented on www/js/app.interceptor.js
> +      config.params = config.params || {};
` config.params = config.params || {}; `
this part is obsolete, as you are not using the params in this method at all. copy-paste artifact from the server?

2018-12-06 19:22 UTC, dularion commented on www/js/streama.routes.js
> +      currentUser: currentUserResolve
try to avoid pushing just whitespace changes like these

2018-12-06 19:22 UTC, dularion commented on www/templates/main.html
> +                  ng-class="{'active': (profile.id == mainVm.selectedProfile.id)}"
maybe style this similar to the profiles in the server-app, i.e. with the colorful image of each user & then the name. 
The standard active-style might conflict with the blue-tones from the profiles. maybe use a darker shade of grey/black here instead?

2018-12-10 09:07 UTC, Maximbndrnk commented on www/js/streama.routes.js
> +      currentUser: currentUserResolve
ok

2018-12-10 09:10 UTC, Maximbndrnk commented on www/js/core/services/api.service.js
> +          });
probably, not

2018-12-10 13:58 UTC, Maximbndrnk commented on www/templates/main.html
> +          {{profile.profile_name}}
we changed naming on domain after i pushed this, so i changed naming

2018-12-10 13:58 UTC, Maximbndrnk commented on www/js/core/services/api.service.js
> +        }
deleted

2018-12-10 14:35 UTC, Maximbndrnk commented on www/templates/main.html
>          <ion-item menu-close ui-sref="main.dash" ng-click="mainVm.toggleSearch()">
This toggle is the ionic thing, don't think we want to go deep inside, besides we lose the 'logic' menu button. Correct me if I wrong

2019-01-16 19:11 UTC, dularion approved these changes

2019-01-16 19:11 UTC, merged

2019-01-16 19:11 UTC, dularion commented
Very good work! thank you for this!